### ISSUE TITLE
Button for adding Morphs

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/SWT18-Project-09#50]
### Original issue (by @ekrebs5 )
I want a button where the add-text-button and add-image-button are. When I click this button, I get a list of all classes that implement "openInHand". When I select one of them, it does "selected-class new openInHand" in order to easily add it to my presentation.

### User story
As a presentation creator, I would like to have a button which enables me to create any Morph that understands "openInHand" in order to easier add Morphs to my slides

Acceptance criteria:
- [ ] A button with a label similar to "add any Morph" exists
- [ ] Clicking the button brings up a list of all classes that understand "openInHand"
- [ ] Selecting any of those classes executes "*class* new openInHand"

Estimated effort:

**Comment by LeonBein** [comment]
After talking to Justus we decided to not realise this user story.
The reasons for that are:
- All subclasses of Morph implement openInHand but it does not seem to make sense for most
- When clicking in the world, "new morph..."->"from alphabetical list" basically already provides the needed behavior
- We are planning to maybe transform this to a user story that caches recently added Morph types

**Comment by ekrebs5** [comment]
Maybe this could be turned into a mini-tutorial instead? My use case behind this was that I am new to your tool (possibly even new to squeak) and could see the drop-morph-into-presentation-mechanic in action (maybe with other useful examples like charts from StatisticsWorkbench or tables from SpreadSheetTool)

anyway I think you can close this issue

**Comment by MrModder** [comment]
We are closing the issue for now, but are keeping the idea of "recently added Morphs" in mind.
